<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        //->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        //->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/main.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
    <?php
    $form = $this->loginForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('zfcuser/login'));
    $form->setAttribute('method', 'post');
    $form->setAttribute('autocomplete', 'off');
    $form->setAttribute('id', 'sing_in');
    ?>
    <div class="popup-box" id="popup-box-1">
        <div class="close"></div>
        <?php echo $this->form()->openTag($form) ?>
        <div class="top">
            <div class="close"></div>
            <h2>Sing in to</h2>

            <div class="checkbox-help">
                <label>
                    <input type="checkbox" class="help" name="help" value="receive" checked=""/>
                    <span>Receive Help</span>
                </label>
                <label>
                    <input type="checkbox" class="help" name="help" value="provide"/>
                    <span>Provide Help</span>
                </label>
            </div>

        </div>
        <div class="bottom ">
            <div class="login_in">
                <div class="row">
                    <?php echo $this->formInput($form->get('identity')) ?>
                </div>
                <div class="row">
                    <?php echo $this->formInput($form->get('credential')) ?>
                </div>
                <div class="row">
                    <div class="submit-holder">
                        <?php echo $this->formButton($form->get('submit')) ?>
                    </div>
                    <a href="#" class="forgot">Forgot Password?</a>
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="remember" value="remember"/>
                        <span>Remember me</a></span>
                    </label>
                </div>

            </div>
            <div class="via">
                <h3>Sigin In via</h3>
                <a href="/user/login/google" ><img class="google" src="../img/google.png" /></a>
                <a href="/user/login/facebook" ><img src="../img/facebook.png" /></a>
            </div>
        </div>
        <?php echo $this->form()->closeTag() ?>
    </div>

    <?php if ($this->enableRegistration) : ?>
        <?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->escapeUrl($this->redirect) : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
    <?php endif; ?>
        <section id="wrapper">
            <header id="header">
                <ul class="nav_menu">
                    <li><a href="#">Become a service provider</a></li>
                    <li><a href="#">Become a servic receiver</a></li>
                </ul>
                <ul class="searchs">
                    <li><input class="search" type="text" placeholder="SEARCH ERRAND..." id="search_errand" /></li>
                    <li>
                        <select class="search">
                            <option>SELECT CITY</option>
                            <option>New York</option>
                            <option>London</option>
                        </select>
                    </li>
                    <li>
                        <a href="" class="popup-link-1" id="sign_in">Sing in<i class="icon castle"></i></a>
                    </li>
                </ul>
            </header>

            <div class="main">
                <?php echo $this->content; ?>
            </div>

            <footer id="footer">
                <div class="footer-top-row">
                    <div class="container-center">
                        <span>Connect with us</span>
                        <ul class="social_icons">
                            <li><a href=""><i class="icon facebook"></i></a></li>
                            <li><a href=""><i class="icon in"></i></a></li>
                            <li><a href=""><i class="icon ppp"></i></a></li>
                            <li><a href=""><i class="icon twiter"></i></a></li>
                            <li><a href=""><i class="icon youtube"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="footer-bottom-row">
                    <div class="container-center">
                        <ul class="footer_menu">
                            <li><a href="">About us</a></li>
                            <li><a href="">Careers</a></li>
                            <li><a href="">Press</a></li>
                            <li><a href="">Blog</a></li>
                            <li><a href="">Platform</a></li>
                            <li><a href="">Terms & Privacy</a></li>
                        </ul>
                        <div class="about_us">
                            <span>A small intro about as</span>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
                                veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
                                commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit
                                esse cillum dolore eu fugiat nulla pariatur.
                            </p>
                        </div>
                        <div class="payment_options">
                            <span>Payment Options</span>
                            <ul class="payment">
                                <li><a href=""><i class="icon master-logo"></i></a></li>
                                <li><a href=""><i class="icon visa-logo"></i></a></li>
                                <li><a href=""><i class="icon american-logo"></i></a></li>
                                <li><a href=""><i class="icon discover-logo"></i></a></li>
                                <li><a href=""><i class="icon paypal"></i></a></li>
                            </ul>
                            <span class="copy">&copy; Copyright <?php echo date('Y') ?> eRRAND. All Rights Reserved. U.S.</span>
                        </div>
                    </div>
                </div>
            </footer>
        </section>
        <?php echo $this->inlineScript() ?>
    </body>
</html>

