<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        //->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        //->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/main.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <section id="wrapper">
            <header id="header">
                <ul class="nav_menu">
                    <li><a href="#">Become a service provider</a></li>
                    <li><a href="#">Become a servic receiver</a></li>
                </ul>
                <ul class="searchs">
                    <li><input class="search" type="text" placeholder="SEARCH ERRAND..." id="search_errand" /></li>
                    <li>
                        <select class="search">
                            <option>SELECT CITY</option>
                            <option>New York</option>
                            <option>London</option>
                        </select>
                    </li>
                    <li>
                        <a href="" class="popup-link-1" id="sign_in">Sing in<i class="icon castle"></i></a>
                    </li>
                </ul>
            </header>

            <div class="main">
                <?php echo $this->content; ?>
            </div>

            <footer id="footer">
                <div class="footer-top-row">
                    <div class="container-center">
                        <span>Connect with us</span>
                        <ul class="social_icons">
                            <li><a href=""><i class="icon facebook"></i></a></li>
                            <li><a href=""><i class="icon in"></i></a></li>
                            <li><a href=""><i class="icon ppp"></i></a></li>
                            <li><a href=""><i class="icon twiter"></i></a></li>
                            <li><a href=""><i class="icon youtube"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="footer-bottom-row">
                    <div class="container-center">
                        <ul class="footer_menu">
                            <li><a href="">About us</a></li>
                            <li><a href="">Careers</a></li>
                            <li><a href="">Press</a></li>
                            <li><a href="">Blog</a></li>
                            <li><a href="">Platform</a></li>
                            <li><a href="">Terms & Privacy</a></li>
                        </ul>
                        <div class="about_us">
                            <span>A small intro about as</span>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
                                veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
                                commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit
                                esse cillum dolore eu fugiat nulla pariatur.
                            </p>
                        </div>
                        <div class="payment_options">
                            <span>Payment Options</span>
                            <ul class="payment">
                                <li><a href=""><i class="icon master-logo"></i></a></li>
                                <li><a href=""><i class="icon visa-logo"></i></a></li>
                                <li><a href=""><i class="icon american-logo"></i></a></li>
                                <li><a href=""><i class="icon discover-logo"></i></a></li>
                                <li><a href=""><i class="icon paypal"></i></a></li>
                            </ul>
                            <span class="copy">&copy; Copyright <?php echo date('Y') ?> eRRAND. All Rights Reserved. U.S.</span>
                        </div>
                    </div>
                </div>
            </footer>
        </section>
        <?php echo $this->inlineScript() ?>
    </body>
</html>

