
<article class="description_block">
    <ul>
        <li class="moving"><a href="#"><img src="img/moving.png" /></a></li>
        <li class="packing"><a href="#"><img src="img/packing.png" /></a></li>
        <li class="moving"><i class="icon logo"></i><a href="#"> <img src="img/academic.png" /></a></li>
        <li class="packing"><a href="#"><img src="img/gardening.png" /></a><a href="#"><img src="img/fashion.png" /></a></li>
        <li class="moving"><a href="#"><img src="img/dog.png" /></a></li>
    </ul>
</article>
<article class="features-block">
    <div class="container-center">
        <h1><?php echo $this->translate('Lorem ipsum dolor sit amet') ?></h1>
        <span><?php echo $this->translate('Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod') ?></span>
        <ul>
            <li class="one">
                <a href="#"><img src="img/one.png" /></a>
                <h3><?php echo $this->translate('Tell Us What You Need') ?></h3>
                <p>
                    <?php echo $this->translate('Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
                    veniam, quis') ?>
                </p>
            </li>
            <li class="two">
                <a href="#"><img src="img/two.png" /></a>
                <h3><?php echo $this->translate('Choose a Task') ?></h3>
                <p>
                    <?php echo $this->translate('Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
                    veniam, quis') ?>
                </p>
            </li>
            <li class="three">
                <a href="#"><img src="img/three.png" /></a>
                <h3><?php echo $this->translate('Sit Back and Relax') ?></h3>
                <p>
                    <?php echo $this->translate('Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
                    veniam, quis') ?>
                </p>
            </li>
        </ul>
    </div>
</article>
<article class="search-block">
    <div class="search_errands">
        <input type="text" placeholder="Search eRRAND..." class="search_errand" />
    </div>
</article>
<article class="help-block">
    <ul class="help">
        <li>
            <h2><?php echo $this->translate('I need some Help') ?></h2>
            <a href="user/register" class="sing_buttom">Register me</a>
        </li>
        <li>
            <h2><?php echo $this->translate('I am here to Help') ?></h2>
            <a href="#" class="sing_buttom">Lets do it</a>
        </li>
    </ul>
</article>
<article class="best-block">
    <div class="best">
        <h2><?php echo $this->translate('This Is Why We Are The Best?') ?></h2>
        <ul>
            <li>
                <img src="img/people.png">
                <h3><?php echo $this->translate('Reseive Help</br>Simple and Fast') ?></h3>
            </li>
            <li>
                <img class="clock" src="img/clock.png">
                <h3><?php echo $this->translate('Save Your</br>Time and Effort') ?></h3>
            </li>
            <li>
                <img src="img/packet.png">
                <h3><?php echo $this->translate('Track Your</br>WorkProgress') ?></h3>
            </li>
            <li>
                <img class="q" src="img/q.png">
                <h3><?php echo $this->translate('With Safety</br>Guaranteed') ?></h3>
            </li>
        </ul>
        <a href="#" class="sing_buttom">Join Now</a>
    </div>
</article>

